{{ if .Values.bigbang.enabled }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  ref:
    branch: {{ .Values.bigbang.branch }}
  secretRef:
    name: private-git
  url: {{ .Values.bigbang.repo }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  decryption:
    provider: {{ .Values.cluster.decryption_provider }}
  interval: 1m
  path: {{ .Values.bigbang.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: environment-repo
{{ end }}
