

--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: rancher
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: "cert-manager"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: "letsencrypt-staging"
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: {{ .Values.letsEncrypt.email }}
    privateKeySecretRef:
      name: "letsencrypt-staging"
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cluster.domain }}
      dns01:
        route53:
          region: {{ .Values.cluster.aws_region }}
          hostedZoneID: {{ .Values.cluster.hosted_zone_id }}
--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: rancher
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: "cert-manager"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: "letsencrypt-production"
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: {{ .Values.letsEncrypt.email }}
    privateKeySecretRef:
      name: "letsencrypt-production"
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cluster.domain }}
      dns01:
        route53:
          region: {{ .Values.cluster.aws_region }}
          hostedZoneID: {{ .Values.cluster.hosted_zone_id }}
