{{ if .Values.longhorn.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.longhorn.namespace }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 60s
  url: {{ .Values.longhorn.chart_repo }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: {{ .Values.longhorn.namespace }}
spec:
  chart:
    spec:
      chart: longhorn
      interval: 1m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: {{ .Values.longhorn.chart_version }}
  interval: 1m0s
  targetNamespace: {{ .Values.longhorn.namespace }}

  dependsOn:
    - name: istio
      namespace: bigbang
{{ end }}
