


apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      interval: 1m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      version: 2.8.1
  interval: 1m0s
  targetNamespace: kube-system
